- kafka-operator/.ci/integration-tests/hcloud-centos-8/cluster.yaml
- kafka-operator/.ci/integration-tests/hcloud-centos-8/test.sh
- monitoring-operator/.ci/integration-tests/hcloud-centos-8/cluster.yaml
- monitoring-operator/.ci/integration-tests/hcloud-centos-8/test.sh
- nifi-operator/.ci/integration-tests/hcloud-centos-8/cluster.yaml
- nifi-operator/.ci/integration-tests/hcloud-centos-8/test.sh
- opa-operator/.ci/integration-tests/hcloud-centos-8/cluster.yaml
- opa-operator/.ci/integration-tests/hcloud-centos-8/test.sh
- spark-operator/.ci/integration-tests/hcloud-centos-8/cluster.yaml
- spark-operator/.ci/integration-tests/hcloud-centos-8/test.sh
- zookeeper-operator/.ci/integration-tests/hcloud-centos-8/cluster.yaml
- zookeeper-operator/.ci/integration-tests/hcloud-centos-8/test.sh
I added profiles for the new Hetzner (HCloud) clusters that T2 can build.
They were successfully tested in manually started test runs:
- https://ci.stackable.tech/view/02%20Component%20Tests%20(flex)/job/Kafka%20Operator%20Integration%20Tests%20(flex)/8/
- https://ci.stackable.tech/view/02%20Component%20Tests%20(flex)/job/Monitoring%20Operator%20Integration%20Tests%20(flex)/14/
- https://ci.stackable.tech/view/02%20Component%20Tests%20(flex)/job/NiFi%20Operator%20Integration%20Tests%20(flex)/8/
- https://ci.stackable.tech/view/02%20Component%20Tests%20(flex)/job/OPA%20Operator%20Integration%20Tests%20(flex)/7/
- https://ci.stackable.tech/view/02%20Component%20Tests%20(flex)/job/Spark%20Operator%20Integration%20Tests%20(flex)/6/
- …
> Add hcloud tests

- Cargo.lock
- commons/CHANGELOG.md
- commons/Cargo.toml
- commons/src/operator/setup.rs
- commons/src/test/kube.rs
- commons/src/test/prelude.rs
- commons/src/test/repository.rs
- commons/src/test/temporary_resource.rs
- hive-operator/Cargo.toml
- kafka-operator/Cargo.toml
- monitoring-operator/Cargo.toml
- nifi-operator/Cargo.toml
- opa-operator/Cargo.toml
- spark-operator/Cargo.toml
- zookeeper-operator/Cargo.toml
Dependency to `operator-rs` reestablished and reexports for `kube`, `k8s-openapi`, and `schemars` used.
:warning: It could be an issue that the CRDs use tagged versions of `operator-rs` whereas the workspace member `common` uses the `main` branch.
Integration test runs:
* [Zookeeper Operator Integration Tests (flex) #14](https://ci.stackable.tech/view/02%20Component%20Tests%20(flex)/job/Zookeeper%20Operator%20Integration%20Tests%20(flex)/14/) :heavy_check_mark:
> Upgrade all dependencies

- superset-operator/tests/common/superset.rs
The custom secret type for Superset credentials is not used and can be replaced with the built-in type `Opaque`.
> Use secret type Opaque for Superset credentials

- trino-operator/.ci/integration-tests/ionos-centos-8/cluster.yaml
- trino-operator/create_test_cluster.fish
Now that we finally have a released Version of Hive, we can pin its version in the Trino test.
The following run was successful w/ Hive Operator 0.3.0: https://ci.stackable.tech/view/02%20Component%20Tests%20(flex)/job/Trino%20Operator%20Integration%20Tests%20(flex)/7/
The second commit changes the test run in Kind to use the latest development version of Trino. It was NOT tested with a Kind cluster.
> CI: pinned Hive in Trino operator test

- druid-operator/README.md
- hive-operator/README.md
- monitoring-operator/README.md
- superset-operator/README.md
- trino-operator/README.md
- zookeeper-operator/README.md
During the transition to the single repo and K8s, some badges were left behind. This PR fixes the badges.
> fixed badges on README files

- Cargo.lock
- Cargo.toml
- commons/Cargo.toml
- commons/src/test/repository.rs
- deny.toml
- superset-operator/Cargo.toml
- superset-operator/tests/common/superset.rs
- superset-operator/tests/create_cluster.rs
Tests stackabletech/superset-operator#45
Due to the upgrade of the operator framework, the tests of the other operators do not compile anymore. They are disabled for now.
The branch for the superset-operator will be set to `main` as soon as the according pull request is merged.
[![Build Actions Status](https://ci.stackable.tech/job/Superset%20Operator%20Integration%20Tests%20(flex)/badge/icon?subject=Integration%20Tests)](https://ci.stackable.tech/view/02%20Component%20Tests%20(flex)/job/Superset%20Operator%20Integration%20Tests%20(flex)/8/)
> Adapt to reworked superset-operator

- druid-operator/tests/common/druid.rs
- druid-operator/tests/create_cluster.rs
- spark-operator/tests/common/spark.rs
- spark-operator/tests/restart_cluster.rs
- trino-operator/tests/common/trino.rs
In our clusters the nodeport 8081 is already used by a daemonset
> Change the druid nodeport

- Cargo.toml
During the activation of the Druid Operator integration test, we accidentally deactivated the ZooKeeper test, which is fixed by this PR
> reactivated Zookeeper Operator integration test

- commons/src/operator/setup.rs
- create_test_cluster.py
- spark-operator/tests/common/spark.rs
We had multiple users for which the old version worked but for one of them it didn't (with the same Python versions). Importing the importlib.util directly seems to work for both of us
> Python import changes

- airflow-operator/.ci/integration-tests/ionos-centos-8/cluster.yaml
- airflow-operator/.ci/integration-tests/ionos-centos-8/test.sh
Added the files necessary to execute the Airflow integration tests in Jenkins CI.
A test run was executed on this branch, you find the results here: https://ci.stackable.tech/view/02%20Component%20Tests%20(flex)/job/Airflow%20Operator%20Integration%20Tests%20(flex)/5/
After this PR is merged, we can add a nightly Job for Airflow running on `main` branch against the latest nightly binary.
> Airflow in Jenkins CI

- hdfs-operator/.ci/integration-tests/hcloud-centos-8/cluster.yaml
- hdfs-operator/.ci/integration-tests/hcloud-centos-8/test.sh
This adds a CI/Jenkins test running on Hetzner CentOS8 using `kuttl`.
Please see successful test run here: https://ci.stackable.tech/view/02%20Component%20Tests%20(flex)/job/HDFS%20Operator%20Integration%20Tests%20(flex)/4/
> HDFS Tests in CI/Jenkins

- Cargo.lock
- Cargo.toml
- airflow-operator/.ci/integration-tests/ionos-centos-8/test.sh
- create_test_cluster.py
- superset-operator/.ci/integration-tests/ionos-centos-8/test.sh
- superset-operator/Cargo.toml
- superset-operator/tests/common/superset.rs
- superset-operator/tests/create_cluster.rs
* Superset integration tests fixed and re-enabled
* Bitnami PostgreSQL Helm chart upgraded and pinned to version 11.0.0
* Fixed PostgreSQL installation in CI scripts of Superset and Airflow
> Fix Superset integration tests

- hdfs-operator/README.md
- hdfs-operator/tests/kuttl/smoke/02-webhdfs.yaml
> HDFS: Use 3.10-slim instead of bullseye.

- airflow-operator/.ci/integration-tests/hcloud-centos-8/test.sh
As Postgresql and Redis are provisioned **within** the kuttl tests, it is no longer required to prepare them in the test script.
This test run proves it: https://ci.stackable.tech/view/02%20Component%20Tests%20(flex)/job/Airflow%20Operator%20Integration%20Tests%20(flex)/11/
> CI/Airflow: removed Postgresql and Redis

- nifi-operator/tests/kuttl/smoke/00-install-zk.yaml
- nifi-operator/tests/kuttl/smoke/01-install-nifi.yaml
- nifi-operator/tests/kuttl/smoke/02-scale-up-nifi.yaml
- nifi-operator/tests/kuttl/smoke/05-enable-anonymous.yaml
- trino-operator/tests/kuttl/smoke/02-install-check.yaml
- adapted cluster reference to configmap name
- use znode
- python image changed to slim
related to https://github.com/stackabletech/nifi-operator/pull/207
> Adapt to new nifi discovery

- README.md
- create_test_cluster.py
The flag `--prometheus` will install the prometheus operator stack and a general ServiceMonitor as described in https://docs.stackable.tech/home/monitoring.html
fixes https://github.com/stackabletech/integration-tests/issues/125
> Added prometheus to create_test_cluster.py

- create_test_cluster.py
Prometheus was only scraping default namespace, which did not work with the random generated kuttl namespaces.
> Added namespaceSelector any to scrape all namespaces

- hbase-operator/tests/smoke/00-assert.yaml
- hbase-operator/tests/smoke/01-assert.yaml
- hbase-operator/tests/smoke/02-assert.yaml
- hbase-operator/tests/smoke/02-install-hbase.yaml
- Updated tests to run against version 2.4.9 (and upped some timeouts)
- see [PR 133](https://github.com/stackabletech/hbase-operator/pull/133): no smoke-testable changes
> hbase: tests against version 2.4.9

- airflow-operator/.ci/integration-tests/hcloud-centos-8/cluster.yaml
- druid-operator/.ci/integration-tests/hcloud-centos-8/cluster.yaml
- hbase-operator/.ci/integration-tests/hcloud-centos-8/cluster.yaml
- hdfs-operator/.ci/integration-tests/hcloud-centos-8/cluster.yaml
- hive-operator/.ci/integration-tests/hcloud-centos-8/cluster.yaml
- kafka-operator/.ci/integration-tests/hcloud-centos-8/cluster.yaml
- nifi-operator/.ci/integration-tests/hcloud-centos-8/cluster.yaml
- opa-operator/.ci/integration-tests/hcloud-centos-8/cluster.yaml
- spark-operator/.ci/integration-tests/hcloud-centos-8/cluster.yaml
- superset-operator/.ci/integration-tests/hcloud-centos-8/cluster.yaml
- trino-operator/.ci/integration-tests/hcloud-centos-8/cluster.yaml
- zookeeper-operator/.ci/integration-tests/hcloud-centos-8/cluster.yaml
Formerly, the integration tests were run against the latest nightly version of the "operator under test" but the other (collaborating) operators were the latest release versions (T2's default). 
As we decided in the architecture meeting, the nightly integration tests should be run with all operators' nightly versions. Since this is now possible as of version `2.11.0` of T2, we changed the cluster definition files accordingly.
The HDFS integration test was run to prove that the change is effective: https://ci.stackable.tech/view/02%20Component%20Tests%20(flex)/job/HBase%20Operator%20Integration%20Tests%20(flex)/10/
> CI tests: set all not-tested operators to latest NIGHTLY

- .github/workflows/reviewdog.yaml
Adopting because the 5 previous commits from dependabot did not  update the comnments. Not sure if this is the correct approach or we should either
* Use renovatebot
* Remove the comments
* something else
> Update dependecy comments of renovate bot

- airflow-operator/tests/kuttl/smoke/02-install-airflow-cluster.yaml
Update Airflow version to 2.2.4-python3.9
Tests stackabletech/airflow-operator#55
> Update Airflow version to 2.2.4-python3.9

- hive-operator/tests/kuttl/smoke/requirements.txt
Caused problems: Cannot install -r /tmp/requirements.txt (line 1) and thrift==0.15.0 because these package versions have conflicting dependencies.
> Downgrade pip package thrift to 0.13.0

- trino-operator/tests/kuttl/smoke/01-install-trino.yaml
- removed node environment for https://github.com/stackabletech/trino-operator/pull/183
> Removed node environment from custom resource
