Cargo.lock
Cargo.toml
commons/Cargo.toml
commons/src/operator/checks.rs
commons/src/operator/mod.rs
deny.toml
druid-operator/Cargo.toml
kafka-operator/tests/common/checks.rs
nifi-operator/tests/common/checks.rs
opa-operator/tests/common/checks.rs
superset-operator/Cargo.toml
superset-operator/README.md
superset-operator/tests/common/checks.rs
superset-operator/tests/common/mod.rs
superset-operator/tests/common/service.rs
superset-operator/tests/common/superset.rs
superset-operator/tests/create_cluster.rs
zookeeper-operator/tests/common/checks.rs

Tests stackabletech/superset-operator#7

Create superset operator tests

---

trino-operator/.ci/integration-tests/ionos-centos-8/cluster.yaml
trino-operator/.ci/integration-tests/ionos-centos-8/test.sh

Execution of the Trino integration test in our CI.
The test has successfully run, see https://ci.stackable.tech/view/02%20Component%20Tests%20(flex)/job/Trino%20Operator%20Integration%20Tests%20(flex)/6/

CI: added Trino test

---

superset-operator/.ci/integration-tests/ionos-centos-8/cluster.yaml
superset-operator/.ci/integration-tests/ionos-centos-8/test.sh

Execution of the Superset integration test in our CI.
The test has successfully run, see https://ci.stackable.tech/view/02%20Component%20Tests%20(flex)/job/Superset%20Operator%20Integration%20Tests%20(flex)/2/

CI: added Superset integration tests

---

.github/workflows/docker.yml

Added empty action to prepare Dockerized tests

---

Cargo.lock
Cargo.toml
create_test_cluster.py
kafka-operator/.ci/integration-tests/ionos-centos-8/cluster.yaml
kafka-operator/.ci/integration-tests/ionos-centos-8/test.sh
kafka-operator/Cargo.toml
kafka-operator/tests/common/kafka.rs
kafka-operator/tests/common/zookeeper.rs
kafka-operator/tests/monitoring.rs

Also fixes #77, since that was blocking this PR.
Pending issues:

Adapt Kafka tests for STFU rework

---

spark-operator/tests/common/spark.rs

Depends on: https://github.com/stackabletech/spark-operator/pull/245

Bugfix: update Spark tests to latest CRD.

---

README.md
create_test_cluster.py

- Allow specifying multiple operators to install
- Allow specifying a directory with resources to apply

Adds changes I made to the create_test_cluster.py script for the demo during the office hours call.

---

spark-operator/.ci/integration-tests/hcloud-centos-8/cluster.yaml
spark-operator/.ci/integration-tests/hcloud-centos-8/test.sh

CI definition and scripts for Jenkins. The test ran successfully on this branch: https://ci.stackable.tech/view/02%20Component%20Tests%20(flex)/job/Spark%20Operator%20Integration%20Tests%20(flex)/20/

CI: Spark Operator integration tests based on kuttl

---

hive-operator/.ci/integration-tests/hcloud-centos-8/cluster.yaml
hive-operator/.ci/integration-tests/hcloud-centos-8/test.sh

CI definition and scripts for Jenkins. The test on this branch ran successfully: https://ci.stackable.tech/view/02%20Component%20Tests%20(flex)/job/Hive%20Operator%20Integration%20Tests%20(flex)/4/

CI: Hive Hive Operator integration tests based on kuttl

---

create_test_cluster.py

Install secret-operator in create_test_cluster

---

trino-operator/tests/kuttl/smoke/01-install-trino.yaml
trino-operator/tests/kuttl/smoke/02-install-check.yaml
trino-operator/tests/kuttl/smoke/04-scale-trino.yaml

- adapted trino resource: `hive` to `hiveConfigMapName`
- python helper image to slim
for https://github.com/stackabletech/trino-operator/pull/131

Adapt to new trino discovery

---

kafka-operator/tests/kuttl/smoke/01-install-kafka.yaml

See https://github.com/stackabletech/kafka-operator/issues/309

Run Kafka tests against 3.1.0

---

create_test_cluster.py

Fixes the following problems:
* If MinIO can't start it will end up with an endless loop (no timeout)
* It produces a lot duplicate debug messages (especially with slow internet connection)

Use kubectl wait to wait till MinIO deployment becomes ready

---

.flake8
.github/workflows/reviewdog.yaml
.markdownlint.yaml
.pylintrc
.yamllint.yaml
superset-operator/kuttl-test.yaml

Adds reviewdog action to run several linters against PRs.
Config for linters was taken from operator templating.

Add reviewdog action

---

README.md
access_services.py
access_services_requirements.txt

For https://github.com/stackabletech/integration-tests/issues/186

access_services.py: downgrade kubernetes lib due to bug

---

create_test_cluster.py

Use cluster's default StorageClass for MinIO

---

nifi-operator/tests/kuttl/smoke/04-assert.yaml
nifi-operator/tests/kuttl/smoke/04-prepare-test-nifi.yaml
nifi-operator/tests/kuttl/smoke/test_nifi_metrics.py

Script that checks if metrics port is opened and a certain metric can be queried.

Added nifi metrics test script

---

access_services.py

access_services.py: Deterministic NodeIP retrival from k8s node

---

README.md

For https://github.com/stackabletech/integration-tests/issues/201

docs: Add docker requirement

---

hbase-operator/tests/smoke/02-install-hbase.yaml

- adapted to PR https://github.com/stackabletech/hbase-operator/pull/162

Adapated to CRD changes

---

superset-operator/.ci/integration-tests/hcloud-centos-8/test.sh

On request by @siegfriedweber, we de-parallelized the integration tests for Superset in Jenkins CI.
Ran successfully: https://ci.stackable.tech/view/02%20Component%20Tests%20(flex)/job/Superset%20Operator%20Integration%20Tests%20(flex)/28/

de-parallelized superset-operator tests
